import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'FR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  EN: {
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      team: 'Team',
      support: 'Support',
      contact: 'Contact',
    },
    hero: {
      title: 'THINK BIG.',
      subtitle: 'GROW MEGAH',
      description: 'Empowering African innovation through cutting-edge technology solutions. From web development to startup consulting, we\'re building the digital future of Cameroon.',
      exploreServices: 'Explore Services',
      contactUs: 'Contact Us',
    },
    mission: {
      title: 'Our Mission',
      description: 'To revolutionize the African tech landscape by providing world-class technology solutions, fostering innovation, and empowering the next generation of African tech leaders.',
      innovation: 'Innovation',
      innovationDesc: 'Cutting-edge solutions that push the boundaries of what\'s possible in African tech.',
      community: 'Community',
      communityDesc: 'Building a strong network of tech professionals and entrepreneurs across Africa.',
      globalImpact: 'Global Impact',
      globalImpactDesc: 'Connecting African innovation with global markets and opportunities.',
    },
    services: {
      title: 'What We Do',
      description: 'From concept to deployment, we provide comprehensive technology solutions that drive growth and innovation.',
      webDev: 'Web & App Development',
      webDevDesc: 'Modern, scalable applications built with cutting-edge technology.',
      consulting: 'Startup Consulting',
      consultingDesc: 'Strategic guidance to transform your ideas into successful businesses.',
      documents: 'Document Processing',
      documentsDesc: 'Efficient document services for travel and business needs.',
      platform: 'MegaConnect Platform',
      platformDesc: 'Connecting talent with opportunities across Africa.',
      viewAll: 'View All Services',
    },
    cta: {
      title: 'Ready to Grow MEGAH?',
      description: 'Join us in building the future of African technology. Let\'s create something extraordinary together.',
      getStarted: 'Get Started Today',
    },
    about: {
      heroTitle: 'About',
      heroCompany: 'MEGAH GROUP OF COMPANIES',
      heroSubtitle: 'Building the future of African technology, one innovation at a time.',
      storyTitle: 'Our Story',
      storyP1: 'MEGAH Group of Companies was born from a vision to transform Africa\'s technological landscape. Founded in the vibrant city of Douala, Cameroon, we emerged from the understanding that Africa\'s greatest asset is its people and their unlimited potential for innovation.',
      storyP2: 'Our journey began with a simple belief: that with the right tools, mentorship, and opportunities, African entrepreneurs and developers can compete globally while solving local challenges. Today, we stand as a testament to that belief.',
      storyP3: 'From our headquarters in Douala, we\'ve expanded our reach across Cameroon and beyond, empowering startups, training the next generation of tech leaders, and building solutions that matter to our communities.',
      foundedTitle: 'Founded in Cameroon',
      foundedDesc: 'Rooted in African excellence and innovation',
      communityTitle: 'Community First',
      communityDesc: 'Building solutions that empower our people',
      standardsTitle: 'Global Standards',
      standardsDesc: 'World-class solutions with local understanding',
      foundationTitle: 'Our Foundation',
      foundationDesc: 'The principles that guide everything we do',
      mission: 'Mission',
      missionDesc: 'To revolutionize the African tech landscape by providing world-class technology solutions, fostering innovation, and empowering the next generation of African tech leaders.',
      vision: 'Vision',
      visionDesc: 'To become Africa\'s leading technology company, recognized globally for innovation, excellence, and our contribution to the continent\'s digital transformation.',
      values: 'Values',
      valuesInnovation: 'Innovation',
      valuesInnovationDesc: 'Pushing boundaries with creative solutions',
      valuesExcellence: 'Excellence',
      valuesExcellenceDesc: 'Delivering quality in everything we do',
      valuesIntegrity: 'Integrity',
      valuesIntegrityDesc: 'Building trust through transparency',
      valuesCommunity: 'Community',
      valuesCommunityDesc: 'Growing together as one Africa',
      cultureTitle: 'Our Culture',
      cultureDesc: 'Innovation, Legacy, and Energy - the three pillars that define the MEGAH GROUP spirit',
      cultureInnovation: 'Innovation',
      cultureInnovationDesc: 'We constantly push the boundaries of what\'s possible, turning bold ideas into reality through cutting-edge technology and creative problem-solving.',
      cultureLegacy: 'Legacy',
      cultureLegacyDesc: 'Every project we undertake is designed to leave a lasting positive impact on our communities and contribute to Africa\'s technological advancement.',
      cultureEnergy: 'Energy',
      cultureEnergyDesc: 'Our youthful spirit and passion for technology drive us to work with enthusiasm, creativity, and an unwavering commitment to excellence.',
    },
    team: {
      heroTitle: 'Our',
      heroHighlight: 'Team',
      heroSubtitle: 'Meet the passionate innovators driving Africa\'s tech revolution',
      founderRole: 'Founder & CEO',
      ceoBio: 'Visionary leader, Pastor, and passionate servant of God. Founder of MEGAH GROUP OF COMPANIES and BALM GLOBAL Ministry (India). Walking daily with deep conviction to use technology, writing, and pastoral calling to impact lives and bring glory to God. Expert in full-stack development, committed to empowering African tech talent while spreading Christ\'s message through digital innovation. As a developer, designer, writer, and minister, every project carries excellence, creativity, and divine purpose.',
      specialties: 'Specialties:',
      fullStackDev: 'Full-Stack Development',
      digitalInnovation: 'Digital Innovation',
      pastorMinistry: 'Pastor & Ministry',
      writingContent: 'Writing & Content Creation',
      graphicsDesign: 'Graphics Design',
      valuesDriveTitle: 'What Drives Us',
      valuesDriveSubtitle: 'The values and principles that unite our team in building extraordinary solutions',
      innovationFirst: 'Innovation First',
      innovationFirstDesc: 'We constantly push boundaries and embrace new technologies to create groundbreaking solutions.',
      collaboration: 'Collaboration',
      collaborationDesc: 'Our diverse expertise combines to deliver solutions greater than the sum of our parts.',
      excellence: 'Excellence',
      excellenceDesc: 'Every project receives our full attention to detail and commitment to quality.',
      joinTitle: 'Join Our Mission',
      joinSubtitle: 'Ready to be part of Africa\'s tech revolution? We\'re always looking for talented individuals to join our team.',
      viewPositions: 'View Open Positions',
      achievementsTitle: 'Our Achievements & Recognitions',
      achievementsSubtitle: 'Celebrating the milestones and certifications that mark our journey of excellence',
      projectsDelivered: 'Projects Delivered',
      projectsDeliveredDesc: '50+ successful projects delivered across web, mobile, and consulting services',
      certifiedPros: 'Certified Professionals',
      certifiedProsDesc: 'Team members certified in React, Python, Agile/Scrum, and Google Cloud',
      industryRecognition: 'Industry Recognition',
      industryRecognitionDesc: 'Recognized as emerging tech innovators in Cameroon\'s digital ecosystem',
      clientSatisfaction: 'Client Satisfaction',
      clientSatisfactionDesc: '98% client satisfaction rate with long-term partnership focus',
    },
    contact: {
      heroTitle: 'Contact',
      heroHighlight: 'Us',
      heroSubtitle: 'Ready to transform your ideas into reality? Let\'s start the conversation today.',
      sendMessage: 'Send Us a Message',
      formDesc: 'Fill out the form below and we\'ll get back to you within 24 hours.',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email Address',
      phone: 'Phone Number',
      company: 'Company/Organization',
      service: 'Service Interest',
      selectService: 'Select a service',
      webDevelopment: 'Web & App Development',
      startupConsulting: 'Startup Consulting',
      documentProcessing: 'Document Processing',
      megaconnect: 'MegaConnect Platform',
      other: 'Other',
      budget: 'Project Budget Range',
      selectBudget: 'Select budget range',
      under1k: 'Under $1,000',
      budget1k5k: '$1,000 - $5,000',
      budget5k10k: '$5,000 - $10,000',
      budget10k25k: '$10,000 - $25,000',
      budget25kPlus: '$25,000+',
      discuss: 'Prefer to discuss',
      message: 'Project Details',
      messagePlaceholder: 'Tell us about your project, goals, timeline, and any specific requirements...',
      timeline: 'Preferred Timeline',
      selectTimeline: 'Select timeline',
      asap: 'ASAP',
      oneMonth: 'Within 1 month',
      twoThree: '2-3 months',
      sixMonths: 'Within 6 months',
      flexible: 'Flexible',
      sending: 'Sending...',
      sendBtn: 'Send Message',
      officeLocation: 'Office Location',
      officeAddress: 'MEGAH Group of Companies',
      city: 'Douala, Cameroon',
      region: 'Central Africa',
      businessHours: 'Business Hours',
      monday: 'Monday - Friday: 8:00 AM - 6:00 PM',
      saturday: 'Saturday: 9:00 AM - 2:00 PM',
      sunday: 'Sunday: Closed',
      emergency: '*Emergency support available 24/7',
      socialMedia: 'Social Media',
      followUs: 'Connect with us on social media',
      mapTitle: 'Visit Us',
      mapDesc: 'Find us at our Douala office',
      ctaTitle: 'Ready to Start Your Project?',
      ctaDesc: 'Let\'s discuss how we can help you achieve your goals. Get in touch today!',
      ctaBtn: 'Get Started Now',
    },
    support: {
      heroTitle: 'Support',
      heroHighlight: 'MEGAH',
      heroSubtitle: 'Join us in empowering communities and fostering innovation across Africa',
      impactTitle: 'Our Impact',
      impactDesc: 'Together, we\'re making a difference in communities across Africa',
      beneficiaries: 'Beneficiaries Reached',
      beneficiariesDesc: 'Individuals directly impacted by our programs',
      programs: 'Active Programs',
      programsDesc: 'Ongoing initiatives across education, tech, and community development',
      communities: 'Communities Served',
      communitiesDesc: 'Villages and cities where we\'re creating lasting change',
      volunteers: 'Volunteers & Partners',
      volunteersDesc: 'Dedicated individuals and organizations supporting our mission',
      paymentTitle: 'Payment Methods',
      paymentDesc: 'Choose your preferred method to contribute',
      momo: 'Mobile Money (MTN)',
      momoDesc: 'Send directly via MTN Mobile Money',
      orangeMoney: 'Orange Money',
      orangeMoneyDesc: 'Convenient Orange Money transfer',
      bankTransfer: 'Bank Transfer (India Bank)',
      bankTransferDesc: 'Direct bank transfer to India Bank',
      accountNumber: 'Account Number',
      accountName: 'Account Name',
      ifscCode: 'IFSC Code',
      copyNumber: 'Copy Account Number',
      copyDetails: 'Copy Details',
      supportTitle: 'Ways to Support',
      individual: 'Individual Sponsorship',
      individualDesc: 'Support our mission with personal contributions',
      individualBenefit1: 'Monthly impact reports',
      individualBenefit2: 'Direct community connection',
      individualBenefit3: 'Tax-deductible donations',
      corporate: 'Corporate Partnership',
      corporateDesc: 'Partner with us for lasting community impact',
      corporateBenefit1: 'Brand visibility opportunities',
      corporateBenefit2: 'Employee engagement programs',
      corporateBenefit3: 'Customized partnership packages',
      community: 'Community Support',
      communityDesc: 'Join grassroots efforts in your area',
      communityBenefit1: 'Volunteer opportunities',
      communityBenefit2: 'Skill-sharing programs',
      communityBenefit3: 'Local event participation',
      contactTitle: 'Get in Touch Directly',
      contactDesc: 'Prefer a direct conversation? Reach out to our partnerships team',
      emailUs: 'Email Us',
      callUs: 'Call Us',
    },
    terms: {
      heroTitle: 'Terms &',
      heroHighlight: 'Privacy',
      heroSubtitle: 'Our commitment to transparency and protecting your rights',
      termsTitle: 'Terms & Conditions',
      lastUpdated: 'Last updated: January 2024',
      acceptance: '1. Acceptance of Terms',
      acceptanceText: 'By accessing and using the services of MEGAH Group of Companies ("MEGAH", "we", "us", or "our"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.',
      serviceDesc: '2. Service Description',
      serviceDescText: 'MEGAH provides technology services including but not limited to web and mobile application development, startup consulting, document processing, and the MegaConnect job platform. We reserve the right to modify, suspend, or discontinue any aspect of our services at any time.',
      clientResp: '3. Client Responsibilities',
      clientRespItems: ['Provide accurate and complete information for all service requests', 'Respond promptly to requests for information or feedback', 'Make timely payments according to agreed terms', 'Respect intellectual property rights of MEGAH and third parties', 'Use our services in compliance with applicable laws and regulations'],
      paymentTerms: '4. Payment Terms',
      paymentTermsText: 'Payment terms vary by service type and are specified in individual project agreements. Generally, we require a deposit before starting work, with remaining payments due according to project milestones. Late payments may incur additional fees. All prices are in USD unless otherwise specified.',
      intellectualProperty: '5. Intellectual Property',
      intellectualPropertyText: 'Upon full payment, clients receive rights to custom-developed work as specified in project agreements. MEGAH retains rights to general methodologies, processes, and any pre-existing intellectual property. We reserve the right to showcase completed work in our portfolio unless otherwise agreed in writing.',
      liability: '6. Limitation of Liability',
      liabilityText: 'MEGAH\'s liability is limited to the amount paid for the specific service in question. We are not liable for indirect, incidental, special, or consequential damages. Our services are provided "as is" without warranties, though we strive for excellence in all deliverables.',
      termination: '7. Termination',
      terminationText: 'Either party may terminate services with written notice. Upon termination, payment is due for all work completed to date. MEGAH will provide all completed deliverables upon receipt of final payment.',
      governingLaw: '8. Governing Law',
      governingLawText: 'These terms are governed by the laws of Cameroon. Any disputes will be resolved through arbitration in Douala, Cameroon, or through competent courts in Cameroon.',
      privacyTitle: 'Privacy Policy',
      infoCollect: '1. Information We Collect',
      infoCollectIntro: 'We collect information you provide directly to us, such as:',
      infoCollectItems: ['Contact information (name, email, phone number)', 'Business information (company name, industry, project details)', 'Payment information (processed securely through third-party providers)', 'Communication records (emails, meeting notes, project communications)', 'Website usage data (through cookies and analytics tools)'],
      infoUse: '2. How We Use Your Information',
      infoUseIntro: 'We use collected information to:',
      infoUseItems: ['Provide and improve our services', 'Communicate with you about projects and services', 'Process payments and manage accounts', 'Send relevant business updates and marketing communications', 'Comply with legal obligations', 'Analyze usage patterns to improve our website and services'],
      infoSharing: '3. Information Sharing',
      infoSharingIntro: 'We do not sell, trade, or rent your personal information. We may share information with:',
      infoSharingItems: ['Service providers who assist in our operations (under confidentiality agreements)', 'Legal authorities when required by law', 'Business partners when you explicitly consent', 'Successors in case of business transfer (with notice to you)'],
      dataSecurity: '4. Data Security',
      dataSecurityText: 'We implement appropriate technical and organizational measures to protect your information, including encryption, secure data transmission, and restricted access controls. However, no method of transmission over the internet is 100% secure.',
      yourRights: '5. Your Rights',
      yourRightsIntro: 'You have the right to:',
      yourRightsItems: ['Access your personal information', 'Correct inaccurate information', 'Request deletion of your information', 'Object to processing of your information', 'Withdraw consent for marketing communications', 'Port your data to another service provider'],
      cookies: '6. Cookies and Tracking',
      cookiesText: 'We use cookies and similar technologies to enhance your experience, analyze usage, and improve our services. You can control cookie settings through your browser preferences.',
      internationalTransfers: '7. International Transfers',
      internationalTransfersText: 'Your information may be transferred to and processed in countries other than Cameroon. We ensure appropriate safeguards are in place for such transfers.',
      contactUs: '8. Contact Us',
      contactUsIntro: 'For questions about these terms or privacy practices, contact us at:',
      contactEmail: 'megahgroupsofcompanies@gmail.com',
      contactAddress: 'MEGAH Group of Companies, Douala, Cameroon',
      contactPhone: '+237 675859441',
      policyUpdates: 'Policy Updates',
      policyUpdatesText: 'We may update these policies periodically. We will notify you of significant changes via email or through our website. Continued use of our services after changes constitutes acceptance of the updated terms.',
    },
    faq: {
      heroTitle: 'Frequently Asked',
      heroHighlight: 'Questions',
      heroSubtitle: 'Find answers to common questions about our services, processes, and how we can help your business grow',
      categoryGeneral: 'General',
      categoryDevelopment: 'Development Services',
      categoryMegaConnect: 'MegaConnect Platform',
      categoryStartup: 'Startup Consulting',
      categoryDocuments: 'Document Services',
      q1: 'What services does MEGAH Group of Companies offer?',
      a1: 'MEGAH specializes in four main areas: Web & Mobile App Development, Startup Consulting & Mentorship, Document Processing for travel and business needs, and our MegaConnect internship and job platform. We provide comprehensive technology solutions tailored to African markets.',
      q2: 'Where is MEGAH located and which countries do you serve?',
      a2: 'We\'re headquartered in Douala, Cameroon, but we serve clients across Africa and globally. Our services are available in French and English, and we have experience working with clients in over 15 African countries.',
      q3: 'How can I contact MEGAH for my project?',
      a3: 'You can reach us through our contact page, email us at megahgroupsofcompanies@gmail.com, call us at +237 675859441, or visit our office in Douala. We offer free initial consultations to discuss your project needs.',
      q4: 'What technologies do you use for web and app development?',
      a4: 'We use modern, industry-standard technologies including React, React Native, Node.js, Python, and cloud platforms like AWS and Google Cloud. We choose the best technology stack based on your specific project requirements and scalability needs.',
      q5: 'How long does it typically take to develop a web application?',
      a5: 'Project timelines vary based on complexity, but simple websites take 2-4 weeks, while complex web applications can take 2-6 months. We provide detailed project timelines during our initial consultation and keep you updated throughout the development process.',
      q6: 'Do you provide ongoing support and maintenance?',
      a6: 'Yes! We offer comprehensive support packages including bug fixes, security updates, feature enhancements, and technical support. Our maintenance plans are tailored to your specific needs and budget.',
      q7: 'What is MegaConnect and how does it work?',
      a7: 'MegaConnect is our job and internship platform that connects African talent with opportunities across the continent and globally. Job seekers create profiles, employers post positions, and our AI-powered matching system connects the right talent with the right opportunities.',
      q8: 'Do you provide internships at MEGAH?',
      a8: 'Yes! We offer internship programs for students and recent graduates in software development, UI/UX design, project management, and digital marketing. Our internships provide hands-on experience with real projects and mentorship from industry professionals.',
      q9: 'How can companies hire talent through MegaConnect?',
      a9: 'Companies can create employer accounts on MegaConnect, post job openings, and access our talent pool. We also offer recruitment services where our team helps identify and vet candidates based on your specific requirements.',
      q10: 'What type of startup consulting do you provide?',
      a10: 'We offer comprehensive startup consulting including business model development, technical architecture planning, market research, funding strategy, team building guidance, and go-to-market strategy. We work with startups from idea stage to scale-up phase.',
      q11: 'Do you help with funding and investor connections?',
      a11: 'Yes, we assist with funding strategy, pitch deck development, and have connections with investors focused on African startups. While we can\'t guarantee funding, we help prepare startups to be investment-ready and make strategic introductions.',
      q12: 'Can you help validate my business idea?',
      a12: 'Absolutely! Market validation is crucial for startup success. We conduct market research, competitor analysis, customer interviews, and prototype testing to validate your business idea before significant investment in development.',
      q13: 'What document processing services do you offer?',
      a13: 'We assist with visa applications, business registration documents, legal documentation, translation services, apostille and authentication services, and other travel-related paperwork. Our team understands the complexities of African and international documentation requirements.',
      q14: 'How quickly can you process documents?',
      a14: 'Processing times vary by document type and destination country. Simple translations take 1-3 days, while visa applications can take 1-4 weeks depending on the embassy requirements. We offer express processing for urgent requests.',
      q15: 'Do you handle documents for all countries?',
      a15: 'We primarily specialize in documents for African countries and major international destinations including USA, Canada, Europe, and Asia. For specific country requirements, please contact us to confirm our services in your target destination.',
      stillHaveQuestions: 'Still Have Questions?',
      stillHaveQuestionsDesc: 'Our team is here to help. Reach out through any of these channels for personalized assistance.',
      liveChat: 'Live Chat',
      liveChatDesc: 'Get instant answers from our support team',
      startChat: 'Start Chat',
      emailSupport: 'Email Support',
      emailSupportDesc: 'Detailed responses within 24 hours',
      sendEmail: 'Send Email',
      phoneSupport: 'Phone Support',
      phoneSupportDesc: 'Speak directly with our experts',
      callNow: 'Call Now',
      exploreMore: 'Explore More',
      exploreMoreDesc: 'Learn more about our services and how we can help your business succeed',
      viewAllServices: 'View All Services',
      aboutMegah: 'About MEGAH',
    },
    footer: {
      tagline: 'African tech innovation at its finest. Building the future with cutting-edge solutions.',
      slogan: '"Think Big. Grow MEGAH"',
      quickLinks: 'Quick Links',
      aboutUs: 'About Us',
      services: 'Services',
      ourTeam: 'Our Team',
      testimonials: 'Testimonials',
      servicesTitle: 'Services',
      webAppDev: 'Web & App Development',
      startupConsulting: 'Startup Consulting',
      documentProcessing: 'Document Processing',
      megaconnectPlatform: 'MegaConnect Platform',
      connect: 'Connect',
      location: 'Douala, Cameroon',
      emailPrimary: 'megahgroupsofcompanies@gmail.com',
      emailSecondary: 'megahprince82@gmail.com',
      phone: '+237 675859441',
      copyright: '© 2024 MEGAH Group of Companies. All rights reserved.',
      termsConditions: 'Terms & Conditions',
      privacyPolicy: 'Privacy Policy',
    },
  },
  FR: {
    nav: {
      home: 'Accueil',
      about: 'À propos',
      services: 'Services',
      team: 'Équipe',
      support: 'Support',
      contact: 'Contact',
    },
    hero: {
      title: 'PENSEZ GRAND.',
      subtitle: 'GRANDISSEZ MEGAH',
      description: 'Autonomiser l\'innovation africaine grâce à des solutions technologiques de pointe. Du développement web au conseil pour startups, nous construisons l\'avenir numérique du Cameroun.',
      exploreServices: 'Explorer les Services',
      contactUs: 'Contactez-nous',
    },
    mission: {
      title: 'Notre Mission',
      description: 'Révolutionner le paysage technologique africain en fournissant des solutions technologiques de classe mondiale, en favorisant l\'innovation et en responsabilisant la prochaine génération de leaders technologiques africains.',
      innovation: 'Innovation',
      innovationDesc: 'Des solutions de pointe qui repoussent les limites du possible dans la technologie africaine.',
      community: 'Communauté',
      communityDesc: 'Construire un réseau solide de professionnels de la technologie et d\'entrepreneurs à travers l\'Afrique.',
      globalImpact: 'Impact Global',
      globalImpactDesc: 'Connecter l\'innovation africaine avec les marchés et opportunités mondiaux.',
    },
    services: {
      title: 'Ce Que Nous Faisons',
      description: 'Du concept au déploiement, nous fournissons des solutions technologiques complètes qui favorisent la croissance et l\'innovation.',
      webDev: 'Développement Web & Apps',
      webDevDesc: 'Applications modernes et évolutives construites avec une technologie de pointe.',
      consulting: 'Conseil aux Startups',
      consultingDesc: 'Conseils stratégiques pour transformer vos idées en entreprises prospères.',
      documents: 'Traitement de Documents',
      documentsDesc: 'Services de documents efficaces pour les voyages et les besoins professionnels.',
      platform: 'Plateforme MegaConnect',
      platformDesc: 'Connecter les talents avec les opportunités à travers l\'Afrique.',
      viewAll: 'Voir Tous les Services',
    },
    cta: {
      title: 'Prêt à Grandir MEGAH?',
      description: 'Rejoignez-nous pour construire l\'avenir de la technologie africaine. Créons quelque chose d\'extraordinaire ensemble.',
      getStarted: 'Commencer Aujourd\'hui',
    },
    about: {
      heroTitle: 'À propos de',
      heroCompany: 'MEGAH GROUP OF COMPANIES',
      heroSubtitle: 'Construire l\'avenir de la technologie africaine, une innovation à la fois.',
      storyTitle: 'Notre Histoire',
      storyP1: 'MEGAH Group of Companies est né d\'une vision de transformer le paysage technologique africain. Fondé dans la ville dynamique de Douala, au Cameroun, nous avons émergé de la compréhension que le plus grand atout de l\'Afrique est son peuple et son potentiel illimité d\'innovation.',
      storyP2: 'Notre voyage a commencé avec une croyance simple : qu\'avec les bons outils, le mentorat et les opportunités, les entrepreneurs et développeurs africains peuvent rivaliser à l\'échelle mondiale tout en résolvant les défis locaux. Aujourd\'hui, nous sommes un témoignage de cette croyance.',
      storyP3: 'Depuis notre siège à Douala, nous avons étendu notre portée à travers le Cameroun et au-delà, en responsabilisant les startups, en formant la prochaine génération de leaders technologiques et en construisant des solutions qui comptent pour nos communautés.',
      foundedTitle: 'Fondé au Cameroun',
      foundedDesc: 'Enraciné dans l\'excellence et l\'innovation africaines',
      communityTitle: 'Communauté D\'abord',
      communityDesc: 'Construire des solutions qui responsabilisent notre peuple',
      standardsTitle: 'Normes Mondiales',
      standardsDesc: 'Solutions de classe mondiale avec compréhension locale',
      foundationTitle: 'Notre Fondation',
      foundationDesc: 'Les principes qui guident tout ce que nous faisons',
      mission: 'Mission',
      missionDesc: 'Révolutionner le paysage technologique africain en fournissant des solutions technologiques de classe mondiale, en favorisant l\'innovation et en responsabilisant la prochaine génération de leaders technologiques africains.',
      vision: 'Vision',
      visionDesc: 'Devenir l\'entreprise technologique leader de l\'Afrique, reconnue mondialement pour l\'innovation, l\'excellence et notre contribution à la transformation numérique du continent.',
      values: 'Valeurs',
      valuesInnovation: 'Innovation',
      valuesInnovationDesc: 'Repousser les limites avec des solutions créatives',
      valuesExcellence: 'Excellence',
      valuesExcellenceDesc: 'Fournir de la qualité dans tout ce que nous faisons',
      valuesIntegrity: 'Intégrité',
      valuesIntegrityDesc: 'Construire la confiance par la transparence',
      valuesCommunity: 'Communauté',
      valuesCommunityDesc: 'Grandir ensemble comme une seule Afrique',
      cultureTitle: 'Notre Culture',
      cultureDesc: 'Innovation, Héritage et Énergie - les trois piliers qui définissent l\'esprit MEGAH GROUP',
      cultureInnovation: 'Innovation',
      cultureInnovationDesc: 'Nous repoussons constamment les limites du possible, transformant des idées audacieuses en réalité grâce à une technologie de pointe et à la résolution créative de problèmes.',
      cultureLegacy: 'Héritage',
      cultureLegacyDesc: 'Chaque projet que nous entreprenons est conçu pour laisser un impact positif durable sur nos communautés et contribuer à l\'avancement technologique de l\'Afrique.',
      cultureEnergy: 'Énergie',
      cultureEnergyDesc: 'Notre esprit jeune et notre passion pour la technologie nous poussent à travailler avec enthousiasme, créativité et un engagement inébranlable envers l\'excellence.',
    },
    team: {
      heroTitle: 'Notre',
      heroHighlight: 'Équipe',
      heroSubtitle: 'Rencontrez les innovateurs passionnés qui conduisent la révolution technologique africaine',
      founderRole: 'Fondateur & PDG',
      ceoBio: 'Leader visionnaire, Pasteur et serviteur passionné de Dieu. Fondateur de MEGAH GROUP OF COMPANIES et BALM GLOBAL Ministry (Inde). Marchant quotidiennement avec une profonde conviction d\'utiliser la technologie, l\'écriture et la vocation pastorale pour impacter des vies et apporter la gloire à Dieu. Expert en développement full-stack, engagé à responsabiliser les talents technologiques africains tout en diffusant le message du Christ à travers l\'innovation numérique. En tant que développeur, designer, écrivain et ministre, chaque projet porte l\'excellence, la créativité et un objectif divin.',
      specialties: 'Spécialités:',
      fullStackDev: 'Développement Full-Stack',
      digitalInnovation: 'Innovation Numérique',
      pastorMinistry: 'Pasteur & Ministère',
      writingContent: 'Écriture & Création de Contenu',
      graphicsDesign: 'Conception Graphique',
      valuesDriveTitle: 'Ce Qui Nous Motive',
      valuesDriveSubtitle: 'Les valeurs et principes qui unissent notre équipe dans la création de solutions extraordinaires',
      innovationFirst: 'Innovation D\'abord',
      innovationFirstDesc: 'Nous repoussons constamment les limites et adoptons de nouvelles technologies pour créer des solutions révolutionnaires.',
      collaboration: 'Collaboration',
      collaborationDesc: 'Notre expertise diversifiée se combine pour fournir des solutions supérieures à la somme de nos parties.',
      excellence: 'Excellence',
      excellenceDesc: 'Chaque projet reçoit toute notre attention aux détails et notre engagement envers la qualité.',
      joinTitle: 'Rejoignez Notre Mission',
      joinSubtitle: 'Prêt à faire partie de la révolution technologique africaine? Nous recherchons toujours des personnes talentueuses pour rejoindre notre équipe.',
      viewPositions: 'Voir Les Postes Ouverts',
      achievementsTitle: 'Nos Réalisations & Reconnaissances',
      achievementsSubtitle: 'Célébrer les jalons et certifications qui marquent notre parcours d\'excellence',
      projectsDelivered: 'Projets Livrés',
      projectsDeliveredDesc: 'Plus de 50 projets réussis livrés dans le web, le mobile et les services de conseil',
      certifiedPros: 'Professionnels Certifiés',
      certifiedProsDesc: 'Membres de l\'équipe certifiés en React, Python, Agile/Scrum et Google Cloud',
      industryRecognition: 'Reconnaissance Industrielle',
      industryRecognitionDesc: 'Reconnus comme innovateurs technologiques émergents dans l\'écosystème numérique camerounais',
      clientSatisfaction: 'Satisfaction Client',
      clientSatisfactionDesc: 'Taux de satisfaction client de 98% avec un accent sur les partenariats à long terme',
    },
    contact: {
      heroTitle: 'Contactez',
      heroHighlight: 'Nous',
      heroSubtitle: 'Prêt à transformer vos idées en réalité? Commençons la conversation aujourd\'hui.',
      sendMessage: 'Envoyez-nous un Message',
      formDesc: 'Remplissez le formulaire ci-dessous et nous vous répondrons dans les 24 heures.',
      firstName: 'Prénom',
      lastName: 'Nom de Famille',
      email: 'Adresse Email',
      phone: 'Numéro de Téléphone',
      company: 'Entreprise/Organisation',
      service: 'Service d\'Intérêt',
      selectService: 'Sélectionnez un service',
      webDevelopment: 'Développement Web & Apps',
      startupConsulting: 'Conseil aux Startups',
      documentProcessing: 'Traitement de Documents',
      megaconnect: 'Plateforme MegaConnect',
      other: 'Autre',
      budget: 'Fourchette Budgétaire du Projet',
      selectBudget: 'Sélectionnez la fourchette budgétaire',
      under1k: 'Moins de $1,000',
      budget1k5k: '$1,000 - $5,000',
      budget5k10k: '$5,000 - $10,000',
      budget10k25k: '$10,000 - $25,000',
      budget25kPlus: '$25,000+',
      discuss: 'Préfère discuter',
      message: 'Détails du Projet',
      messagePlaceholder: 'Parlez-nous de votre projet, objectifs, calendrier et exigences spécifiques...',
      timeline: 'Calendrier Préféré',
      selectTimeline: 'Sélectionnez le calendrier',
      asap: 'Dès que possible',
      oneMonth: 'Dans 1 mois',
      twoThree: '2-3 mois',
      sixMonths: 'Dans 6 mois',
      flexible: 'Flexible',
      sending: 'Envoi en cours...',
      sendBtn: 'Envoyer le Message',
      officeLocation: 'Emplacement du Bureau',
      officeAddress: 'MEGAH Group of Companies',
      city: 'Douala, Cameroun',
      region: 'Afrique Centrale',
      businessHours: 'Horaires d\'Ouverture',
      monday: 'Lundi - Vendredi: 8h00 - 18h00',
      saturday: 'Samedi: 9h00 - 14h00',
      sunday: 'Dimanche: Fermé',
      emergency: '*Support d\'urgence disponible 24/7',
      socialMedia: 'Réseaux Sociaux',
      followUs: 'Connectez-vous avec nous sur les réseaux sociaux',
      mapTitle: 'Visitez-Nous',
      mapDesc: 'Trouvez-nous à notre bureau de Douala',
      ctaTitle: 'Prêt à Démarrer Votre Projet?',
      ctaDesc: 'Discutons de la manière dont nous pouvons vous aider à atteindre vos objectifs. Contactez-nous aujourd\'hui!',
      ctaBtn: 'Commencer Maintenant',
    },
    support: {
      heroTitle: 'Soutenez',
      heroHighlight: 'MEGAH',
      heroSubtitle: 'Rejoignez-nous pour responsabiliser les communautés et favoriser l\'innovation à travers l\'Afrique',
      impactTitle: 'Notre Impact',
      impactDesc: 'Ensemble, nous faisons une différence dans les communautés à travers l\'Afrique',
      beneficiaries: 'Bénéficiaires Atteints',
      beneficiariesDesc: 'Personnes directement impactées par nos programmes',
      programs: 'Programmes Actifs',
      programsDesc: 'Initiatives en cours dans l\'éducation, la technologie et le développement communautaire',
      communities: 'Communautés Servies',
      communitiesDesc: 'Villages et villes où nous créons un changement durable',
      volunteers: 'Bénévoles & Partenaires',
      volunteersDesc: 'Individus et organisations dévoués soutenant notre mission',
      paymentTitle: 'Méthodes de Paiement',
      paymentDesc: 'Choisissez votre méthode préférée pour contribuer',
      momo: 'Mobile Money (MTN)',
      momoDesc: 'Envoyez directement via MTN Mobile Money',
      orangeMoney: 'Orange Money',
      orangeMoneyDesc: 'Transfert pratique Orange Money',
      bankTransfer: 'Virement Bancaire (India Bank)',
      bankTransferDesc: 'Virement bancaire direct vers India Bank',
      accountNumber: 'Numéro de Compte',
      accountName: 'Nom du Compte',
      ifscCode: 'Code IFSC',
      copyNumber: 'Copier le Numéro de Compte',
      copyDetails: 'Copier les Détails',
      supportTitle: 'Façons de Soutenir',
      individual: 'Parrainage Individuel',
      individualDesc: 'Soutenez notre mission avec des contributions personnelles',
      individualBenefit1: 'Rapports d\'impact mensuels',
      individualBenefit2: 'Connexion directe avec la communauté',
      individualBenefit3: 'Dons déductibles d\'impôt',
      corporate: 'Partenariat d\'Entreprise',
      corporateDesc: 'Associez-vous à nous pour un impact communautaire durable',
      corporateBenefit1: 'Opportunités de visibilité de marque',
      corporateBenefit2: 'Programmes d\'engagement des employés',
      corporateBenefit3: 'Forfaits de partenariat personnalisés',
      community: 'Soutien Communautaire',
      communityDesc: 'Rejoignez les efforts locaux dans votre région',
      communityBenefit1: 'Opportunités de bénévolat',
      communityBenefit2: 'Programmes de partage de compétences',
      communityBenefit3: 'Participation aux événements locaux',
      contactTitle: 'Contactez-nous Directement',
      contactDesc: 'Préférez une conversation directe? Contactez notre équipe de partenariat',
      emailUs: 'Envoyez-nous un Email',
      callUs: 'Appelez-nous',
    },
    terms: {
      heroTitle: 'Conditions &',
      heroHighlight: 'Confidentialité',
      heroSubtitle: 'Notre engagement envers la transparence et la protection de vos droits',
      termsTitle: 'Termes & Conditions',
      lastUpdated: 'Dernière mise à jour: Janvier 2024',
      acceptance: '1. Acceptation des Conditions',
      acceptanceText: 'En accédant et en utilisant les services de MEGAH Group of Companies ("MEGAH", "nous", "notre"), vous acceptez d\'être lié par les termes et dispositions de cet accord. Si vous n\'acceptez pas de respecter ce qui précède, veuillez ne pas utiliser ce service.',
      serviceDesc: '2. Description des Services',
      serviceDescText: 'MEGAH fournit des services technologiques incluant mais sans s\'y limiter le développement d\'applications web et mobiles, le conseil aux startups, le traitement de documents et la plateforme d\'emploi MegaConnect. Nous nous réservons le droit de modifier, suspendre ou interrompre tout aspect de nos services à tout moment.',
      clientResp: '3. Responsabilités du Client',
      clientRespItems: ['Fournir des informations exactes et complètes pour toutes les demandes de service', 'Répondre rapidement aux demandes d\'information ou de retour', 'Effectuer les paiements en temps voulu selon les conditions convenues', 'Respecter les droits de propriété intellectuelle de MEGAH et des tiers', 'Utiliser nos services conformément aux lois et règlements applicables'],
      paymentTerms: '4. Conditions de Paiement',
      paymentTermsText: 'Les conditions de paiement varient selon le type de service et sont précisées dans les accords de projet individuels. Généralement, nous demandons un acompte avant de commencer le travail, les paiements restants étant dus selon les jalons du projet. Les paiements en retard peuvent entraîner des frais supplémentaires. Tous les prix sont en USD sauf indication contraire.',
      intellectualProperty: '5. Propriété Intellectuelle',
      intellectualPropertyText: 'Après paiement complet, les clients reçoivent les droits sur le travail développé sur mesure tel que spécifié dans les accords de projet. MEGAH conserve les droits sur les méthodologies générales, les processus et toute propriété intellectuelle préexistante. Nous nous réservons le droit de présenter les travaux terminés dans notre portfolio sauf accord contraire par écrit.',
      liability: '6. Limitation de Responsabilité',
      liabilityText: 'La responsabilité de MEGAH est limitée au montant payé pour le service spécifique en question. Nous ne sommes pas responsables des dommages indirects, accessoires, spéciaux ou consécutifs. Nos services sont fournis "en l\'état" sans garanties, bien que nous nous efforcions d\'atteindre l\'excellence dans tous les livrables.',
      termination: '7. Résiliation',
      terminationText: 'Chaque partie peut résilier les services avec un préavis écrit. Lors de la résiliation, le paiement est dû pour tout le travail effectué à ce jour. MEGAH fournira tous les livrables terminés dès réception du paiement final.',
      governingLaw: '8. Droit Applicable',
      governingLawText: 'Ces conditions sont régies par les lois du Cameroun. Tout litige sera résolu par arbitrage à Douala, Cameroun, ou par les tribunaux compétents au Cameroun.',
      privacyTitle: 'Politique de Confidentialité',
      infoCollect: '1. Informations Que Nous Collectons',
      infoCollectIntro: 'Nous collectons les informations que vous nous fournissez directement, telles que:',
      infoCollectItems: ['Informations de contact (nom, email, numéro de téléphone)', 'Informations commerciales (nom de l\'entreprise, secteur, détails du projet)', 'Informations de paiement (traitées de manière sécurisée via des fournisseurs tiers)', 'Dossiers de communication (emails, notes de réunion, communications de projet)', 'Données d\'utilisation du site web (via cookies et outils d\'analyse)'],
      infoUse: '2. Comment Nous Utilisons Vos Informations',
      infoUseIntro: 'Nous utilisons les informations collectées pour:',
      infoUseItems: ['Fournir et améliorer nos services', 'Communiquer avec vous sur les projets et services', 'Traiter les paiements et gérer les comptes', 'Envoyer des mises à jour commerciales et communications marketing pertinentes', 'Respecter les obligations légales', 'Analyser les modèles d\'utilisation pour améliorer notre site web et nos services'],
      infoSharing: '3. Partage d\'Informations',
      infoSharingIntro: 'Nous ne vendons, n\'échangeons ni ne louons vos informations personnelles. Nous pouvons partager des informations avec:',
      infoSharingItems: ['Les prestataires de services qui nous assistent dans nos opérations (sous accords de confidentialité)', 'Les autorités légales lorsque la loi l\'exige', 'Les partenaires commerciaux lorsque vous consentez explicitement', 'Les successeurs en cas de transfert d\'entreprise (avec notification à vous)'],
      dataSecurity: '4. Sécurité des Données',
      dataSecurityText: 'Nous mettons en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos informations, y compris le chiffrement, la transmission sécurisée des données et les contrôles d\'accès restreints. Cependant, aucune méthode de transmission sur Internet n\'est 100% sécurisée.',
      yourRights: '5. Vos Droits',
      yourRightsIntro: 'Vous avez le droit de:',
      yourRightsItems: ['Accéder à vos informations personnelles', 'Corriger les informations inexactes', 'Demander la suppression de vos informations', 'Vous opposer au traitement de vos informations', 'Retirer votre consentement aux communications marketing', 'Transférer vos données vers un autre fournisseur de services'],
      cookies: '6. Cookies et Suivi',
      cookiesText: 'Nous utilisons des cookies et des technologies similaires pour améliorer votre expérience, analyser l\'utilisation et améliorer nos services. Vous pouvez contrôler les paramètres des cookies via les préférences de votre navigateur.',
      internationalTransfers: '7. Transferts Internationaux',
      internationalTransfersText: 'Vos informations peuvent être transférées et traitées dans des pays autres que le Cameroun. Nous veillons à ce que des garanties appropriées soient en place pour de tels transferts.',
      contactUs: '8. Nous Contacter',
      contactUsIntro: 'Pour toute question concernant ces conditions ou pratiques de confidentialité, contactez-nous à:',
      contactEmail: 'megahgroupsofcompanies@gmail.com',
      contactAddress: 'MEGAH Group of Companies, Douala, Cameroun',
      contactPhone: '+237 675859441',
      policyUpdates: 'Mises à Jour des Politiques',
      policyUpdatesText: 'Nous pouvons mettre à jour ces politiques périodiquement. Nous vous informerons des changements importants par email ou sur notre site web. L\'utilisation continue de nos services après les modifications constitue l\'acceptation des conditions mises à jour.',
    },
    faq: {
      heroTitle: 'Questions Fréquemment',
      heroHighlight: 'Posées',
      heroSubtitle: 'Trouvez des réponses aux questions courantes sur nos services, processus et comment nous pouvons aider votre entreprise à croître',
      categoryGeneral: 'Général',
      categoryDevelopment: 'Services de Développement',
      categoryMegaConnect: 'Plateforme MegaConnect',
      categoryStartup: 'Conseil aux Startups',
      categoryDocuments: 'Services de Documents',
      q1: 'Quels services propose MEGAH Group of Companies?',
      a1: 'MEGAH se spécialise dans quatre domaines principaux: Développement Web & Mobile, Conseil et Mentorat pour Startups, Traitement de Documents pour les besoins de voyage et d\'affaires, et notre plateforme de stages et d\'emploi MegaConnect. Nous fournissons des solutions technologiques complètes adaptées aux marchés africains.',
      q2: 'Où se trouve MEGAH et quels pays servez-vous?',
      a2: 'Notre siège est à Douala, au Cameroun, mais nous servons des clients à travers l\'Afrique et dans le monde entier. Nos services sont disponibles en français et en anglais, et nous avons de l\'expérience avec des clients dans plus de 15 pays africains.',
      q3: 'Comment puis-je contacter MEGAH pour mon projet?',
      a3: 'Vous pouvez nous joindre via notre page de contact, nous envoyer un email à megahgroupsofcompanies@gmail.com, nous appeler au +237 675859441, ou visiter notre bureau à Douala. Nous offrons des consultations initiales gratuites pour discuter des besoins de votre projet.',
      q4: 'Quelles technologies utilisez-vous pour le développement web et d\'applications?',
      a4: 'Nous utilisons des technologies modernes et standards de l\'industrie incluant React, React Native, Node.js, Python, et des plateformes cloud comme AWS et Google Cloud. Nous choisissons la meilleure pile technologique en fonction de vos exigences de projet et besoins de scalabilité.',
      q5: 'Combien de temps faut-il généralement pour développer une application web?',
      a5: 'Les délais de projet varient selon la complexité, mais les sites web simples prennent 2-4 semaines, tandis que les applications web complexes peuvent prendre 2-6 mois. Nous fournissons des calendriers de projet détaillés lors de notre consultation initiale et vous tenons informé tout au long du processus de développement.',
      q6: 'Fournissez-vous un support et une maintenance continus?',
      a6: 'Oui! Nous offrons des forfaits de support complets incluant les corrections de bugs, mises à jour de sécurité, améliorations de fonctionnalités et support technique. Nos plans de maintenance sont adaptés à vos besoins et budget spécifiques.',
      q7: 'Qu\'est-ce que MegaConnect et comment ça fonctionne?',
      a7: 'MegaConnect est notre plateforme d\'emploi et de stages qui connecte les talents africains avec des opportunités à travers le continent et dans le monde. Les demandeurs d\'emploi créent des profils, les employeurs publient des postes, et notre système de correspondance alimenté par l\'IA connecte les bons talents avec les bonnes opportunités.',
      q8: 'Proposez-vous des stages chez MEGAH?',
      a8: 'Oui! Nous offrons des programmes de stage pour étudiants et jeunes diplômés en développement logiciel, design UI/UX, gestion de projet et marketing digital. Nos stages offrent une expérience pratique avec de vrais projets et un mentorat de professionnels de l\'industrie.',
      q9: 'Comment les entreprises peuvent-elles recruter des talents via MegaConnect?',
      a9: 'Les entreprises peuvent créer des comptes employeur sur MegaConnect, publier des offres d\'emploi et accéder à notre vivier de talents. Nous offrons également des services de recrutement où notre équipe aide à identifier et évaluer les candidats selon vos exigences spécifiques.',
      q10: 'Quel type de conseil aux startups proposez-vous?',
      a10: 'Nous offrons un conseil complet aux startups incluant le développement de modèles d\'affaires, la planification d\'architecture technique, l\'étude de marché, la stratégie de financement, l\'accompagnement dans la constitution d\'équipe et la stratégie de mise sur le marché. Nous travaillons avec les startups de l\'idée à la phase de croissance.',
      q11: 'Aidez-vous avec le financement et les connexions aux investisseurs?',
      a11: 'Oui, nous aidons avec la stratégie de financement, le développement de pitch decks, et avons des connexions avec des investisseurs focalisés sur les startups africaines. Bien que nous ne puissions pas garantir le financement, nous aidons à préparer les startups à être prêtes pour l\'investissement et faisons des introductions stratégiques.',
      q12: 'Pouvez-vous aider à valider mon idée d\'entreprise?',
      a12: 'Absolument! La validation du marché est cruciale pour le succès d\'une startup. Nous menons des études de marché, des analyses concurrentielles, des entretiens clients et des tests de prototypes pour valider votre idée d\'entreprise avant un investissement significatif dans le développement.',
      q13: 'Quels services de traitement de documents proposez-vous?',
      a13: 'Nous aidons avec les demandes de visa, les documents d\'enregistrement d\'entreprise, la documentation légale, les services de traduction, les services d\'apostille et d\'authentification, et autres formalités liées aux voyages. Notre équipe comprend les complexités des exigences documentaires africaines et internationales.',
      q14: 'À quelle vitesse pouvez-vous traiter les documents?',
      a14: 'Les délais de traitement varient selon le type de document et le pays de destination. Les traductions simples prennent 1-3 jours, tandis que les demandes de visa peuvent prendre 1-4 semaines selon les exigences de l\'ambassade. Nous offrons un traitement express pour les demandes urgentes.',
      q15: 'Gérez-vous les documents pour tous les pays?',
      a15: 'Nous nous spécialisons principalement dans les documents pour les pays africains et les destinations internationales majeures incluant les USA, le Canada, l\'Europe et l\'Asie. Pour des exigences de pays spécifiques, veuillez nous contacter pour confirmer nos services dans votre destination cible.',
      stillHaveQuestions: 'Encore des Questions?',
      stillHaveQuestionsDesc: 'Notre équipe est là pour vous aider. Contactez-nous via l\'un de ces canaux pour une assistance personnalisée.',
      liveChat: 'Chat en Direct',
      liveChatDesc: 'Obtenez des réponses instantanées de notre équipe de support',
      startChat: 'Démarrer le Chat',
      emailSupport: 'Support par Email',
      emailSupportDesc: 'Réponses détaillées sous 24 heures',
      sendEmail: 'Envoyer un Email',
      phoneSupport: 'Support Téléphonique',
      phoneSupportDesc: 'Parlez directement avec nos experts',
      callNow: 'Appeler Maintenant',
      exploreMore: 'Explorer Plus',
      exploreMoreDesc: 'En savoir plus sur nos services et comment nous pouvons aider votre entreprise à réussir',
      viewAllServices: 'Voir Tous les Services',
      aboutMegah: 'À Propos de MEGAH',
    },
    footer: {
      tagline: 'L\'innovation technologique africaine à son meilleur. Construire l\'avenir avec des solutions de pointe.',
      slogan: '"Pensez Grand. Grandissez MEGAH"',
      quickLinks: 'Liens Rapides',
      aboutUs: 'À Propos',
      services: 'Services',
      ourTeam: 'Notre Équipe',
      testimonials: 'Témoignages',
      servicesTitle: 'Services',
      webAppDev: 'Développement Web & Apps',
      startupConsulting: 'Conseil aux Startups',
      documentProcessing: 'Traitement de Documents',
      megaconnectPlatform: 'Plateforme MegaConnect',
      connect: 'Connecter',
      location: 'Douala, Cameroun',
      emailPrimary: 'megahgroupsofcompanies@gmail.com',
      emailSecondary: 'megahprince82@gmail.com',
      phone: '+237 675859441',
      copyright: '© 2024 MEGAH Group of Companies. Tous droits réservés.',
      termsConditions: 'Termes & Conditions',
      privacyPolicy: 'Politique de Confidentialité',
    },
  },
};
